# Generated by Django 2.1.4 on 2018-12-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokeinfo',
            name='no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
