# Generated by Django 2.1.4 on 2018-12-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pokeinfo_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokeinfo',
            name='no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokeinfo',
            name='pokename',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
